---

- name: Perform a LEAPP Upgrade from CentOS 7 to Alma Linux 8
  block:

    - name: Include setup tasks
      include_tasks: setup.yml
      tags: report

    - name: Run the leapp preupgrade tasks
      include_tasks: preupgrade.yml
      tags: report

  when: ansible_distribution_major_version == '7'
