---
- name: Answer leapp prompt
  command: leapp answer --section remove_pam_pkcs11_module_check.confirm=True

- name: Remove problematic modules
  command: rmmod pata_acpi

- name: Call preupgrade playbook
  include_tasks: preupgrade.yml 
