---

- name: Initialize reboot reason as not required
  set_fact:
    reboot_reason: "No reboot required"

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest
  register: yum_upgrade

- name: Test network inhibitor
  shell: "[ $(ip link | egrep '^[0-9]+: eth[0-9]+:' | wc -l) -ge 1 ] && [ $(readlink /sys/class/net/* | grep -v '/virtual/' | wc -l) -ge 2 ] && echo 'yes' || echo 'no'"
  register: nic_inhibitor_check
  changed_when: false
  ignore_errors: yes

- name: Set fact for nic inhibitor presence
  set_fact:
    inhibitor_presence: "{{ 'yes' in nic_inhibitor_check.stdout }}"

- name: Include tasks to rename old naming convention on network interfaces
  include_tasks: 4067471_predictable-nics_3.yml
  when: inhibitor_presence

- name: Reboot system if required
  reboot:
  when: yum_upgrade.changed or inhibitor_presence

- name: Gather package facts
  package_facts:
    manager: auto

- name: Check if elevate-release is installed
  set_fact: 
    elevate_release_installed: "{{ 'elevate-release' in ansible_facts.packages }}"

- name: Install Leapp Repository
  shell: "yum install -y http://repo.almalinux.org/elevate/elevate-release-latest-el$(rpm --eval %rhel).noarch.rpm"
  when: not elevate_release_installed

- name: Install Leapp Packages
  yum:
    name:
      - leapp-upgrade
      - leapp-data-almalinux
    state: latest
#
