---

#- name: Initialize reboot reason as not required
#  set_fact:
#    reboot_reason: "No reboot required"

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest
  register: yum_upgrade

#- name: Reboot system if required
#  reboot:
#  when: yum_upgrade.changed

- name: Gather package facts
  package_facts:
    manager: auto

- name: Check if elevate-release is installed
  set_fact: 
    elevate_release_installed: "{{ 'elevate-release' in ansible_facts.packages }}"

- name: Install Leapp Repository
  shell: "yum install -y http://repo.almalinux.org/elevate/elevate-release-latest-el$(rpm --eval %rhel).noarch.rpm"
  when: not elevate_release_installed

- name: Install Leapp Packages
  yum:
    name:
      - leapp-upgrade
      - leapp-data-almalinux
    state: latest
#
