---
- name: Load leapp preupgrade report
  include_vars:
    file: 'leapp-reports/{{ inventory_hostname }}/var/log/leapp/leapp-report-preupgrade.json'
    name: leapp_preupgrade_report
  when:
    - 'leapp_preupgrade_report is not defined'

- name: Print leapp preupgrade report variable
  debug:
    var: leapp_preupgrade_report
    verbosity: 2

- name: Cleanup previous upgrade reports
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - /var/log/leapp/leapp-report.txt
    - /var/log/leapp/leapp-report.json

- name: Perform leapp upgrade
  command: leapp upgrade
  register: leapp_upgrade

- name: Debug leapp upgrade output
  debug:
    var: leapp_upgrade
    verbosity: 2

- name: Gather leapp upgrade report (TXT)
  fetch:
    src: /var/log/leapp/leapp-report.txt
    dest: 'leapp-reports/{{ inventory_hostname }}/var/log/leapp/leapp-report-upgrade.txt'
    flat: yes

- name: Gather leapp upgrade report (JSON)
  fetch:
    src: /var/log/leapp/leapp-report.json
    dest: 'leapp-reports/{{ inventory_hostname }}/var/log/leapp/leapp-report-upgrade.json'
    flat: yes

- name: Load leapp upgrade report
  include_vars:
    file: 'leapp-reports/{{ inventory_hostname }}/var/log/leapp/leapp-report-upgrade.json'
    name: leapp_upgrade_report

- name: Print leapp upgrade report variable
  debug:
    var: leapp_upgrade_report
    verbosity: 2

- name: Print leapp upgrade statistics
  debug:
    msg: >
      {{ leapp_upgrade_report["entries"] | selectattr("severity", "match", "info") | list | length }} Info Messages,
      {{ leapp_upgrade_report["entries"] | selectattr("severity", "match", "low") | list | length }} Low Severity Issues,
      {{ leapp_upgrade_report["entries"] | selectattr("severity", "match", "high") | list | length }} High Severity Issues

- name: Reboot system
  reboot:
    reboot_timeout: 3600
  when: not leapp_upgrade.failed

#- name: Reboot system
#  debug:
#    msg: "Rebooting system"
#  notify: reboot_system
#  when: not leapp_upgrade.failed
